In [2]:
# Importing dependencies

from learntools.core import binder
import numpy as np

binder.bind(globals())

from learntools_ex import *

print("Setup Complete")

Setup Complete


## **Questions**

## **Q1:** Create a one-dimensional NumPy array of the numbers from 5 to 905, counting by 10?

### **IMPORTANT**: You **don't** have to delete any `q{n}.check()` or `q{n}.hint()` or `q{n}_sol = question_{n}()`. Please make sure that the function name and function signature match the question and the example given. Additionally, all functions should be runnable or your solution will not be evaluated.

In [4]:
def question_1():
    return np.arange(5,905, 10)


q1_sol = question_1()
q1.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q2**: Create the same NumPy array using a Python range and a list? (Hint: create a list)

In [6]:
def question_2():
    list = []
    for i in range(5, 905, 10):
        list.append(i)
    return np.array(list)


q2_sol = question_2()
q2.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q3**: How might you create a NumPy array of the capital letters, A-Z? (Hint: Ever heard of string.ascii_uppercase?)

In [7]:
import string
def question_3():
    array = [character for character in string.ascii_uppercase]
    return np.array(array)
    


q3_sol = question_3()
q3.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q4**: Create a ten-element NumPy array object of all zeros and a six-element NumPy array object of all ones.

In [9]:
def question_4() -> tuple:
    zero_array = np.zeros(10)
    one_array = np.ones(6)
    print(zero_array)
    # Expected: return (sol1, sol2)
    return (zero_array, one_array)

q4_sol_1, q4_sol_2 = question_4()
q4.check()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q5**: Given an 2-D array, print the third column.

In [2]:
input = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])


def question_5(input):

    for i in input[:, 2]:
        print(i)
    return np.array(input[:, 2])
        


q5_sol = question_5(input)
q5.check()


33
66
99


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q6**: Create an array of the shape (3, 4), filled with 64-bit integer zeros.

In [23]:
def question_6():
    return np.zeros(12).reshape(3,4)


q6_sol = question_6()
q6.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q7**: Split an array into 3 equal-sized sub-arrays.

In [5]:
input = np.arange(7, 34, 1).reshape(9, 3)



def question_7(input):
    print((input[:3,:], input[3:6, :], input[6:9, :]))
    return list([input[:3,:], input[3:6, :], input[6:9, :]])


q7_sol_1, q7_sol_2, q7_sol_3 = question_7(input)
q7.check()

(array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]]), array([[25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]]))


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q8**: Return the last 2 elements by each of the first rows of the (3,4) array. 

In [7]:
input = np.arange(1, 13, 1).reshape(3, 4)

# Return the last 2 elements by each of the first 2 rows
def question_8(input):
    return np.array([input[0][-2:], input[1][-2:] ])


q8_sol = question_8(input)
q8.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q9**: Return how many elements are greater than 5 in an array.

In [38]:
input = np.arange(1, 13, 1).reshape(3, 4)


def question_9(input):
    bool_array = input > 5
    return np.sum(bool_array)


q9_sol = question_9(input)
q9.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q10**: Delete the second column from an array and insert the following new column in the same place.

In [42]:
input = np.array([[34, 72, 33], [82, 22, 32], [59, 84, 10]])
insert_data = np.array([[37, 37, 37]])


def question_10(input, insert_data):

    input = np.delete(input, 1, axis=1)
    input = np.insert(input, 1, insert_data, axis= 1)
    return input


q10_sol = question_10(input, insert_data)
q10.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q11**: Compute the Euclidean distance between each pair of consecutive points in a given 2D NumPy array and append the result as a new column.

Euclidian distance between two points $(x_1, y_1)$ and $(x_2, y_2)$ is $\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$.  

In [73]:
input = np.array([[1, 2], [4, 6], [7, 8], [10, 10]])
import math


    
   
    
def question_11(input):
    diff_arr = np.diff(input, axis=0)  # Compute differences
    distance = np.sqrt(diff_arr[:, 0]**2 + diff_arr[:, 1]**2)  # Compute Euclidean distances
    
    distance = np.append(distance, 0).reshape(-1, 1)  # Add 0 for the last row and reshape to a column
    input = np.hstack((input, distance))
    return input
   

q11_sol = question_11(input)
q11.check()
q11.hint()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

<IPython.core.display.Javascript object>

<span style="color:#3366cc">Hint:</span> Compute differences with np.diff(), then calculate Euclidean distances and append a NaN.

## **Q12**: Remove consecutive duplicates from a NumPy array.

In [82]:
input = np.array([[1, 1], [2, 1], [3, 3], [3, 3], [2, 1], [1, 1]])


def question_12(input):
    rep_array = []
    for i in range(len(input)-1, 1, -1):
        if np.array_equal(input[i], input[i-1]) :
            rep_array.append(i)
    for i in rep_array:
        input = np.delete(input, i, axis = 0)
    return input

q12_sol = question_12(input)
q12.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q13**: Given a 2D NumPy array representing strokes, normalize all rows by subtracting the mean of each column and dividing by the standard deviation, but avoid division by zero.
$X_{\text{normalized}} = \frac{X - \mu}{\sigma}$

In [35]:
input = np.array([[10, 20, 30], [15, 24, 33], [8, 18, 29], [14, 22, 32]])


def question_13(input):
    mean = np.mean(input, axis = 0)
    std = np.std(input, axis = 0) 
    std = [value if value != 0 else 1 for value in std ]
    print(std)
    normalized_arr =  (input - mean)/std
    return normalized_arr



q13_sol = question_13(input)
q13.check()

[np.float64(2.8613807855648994), np.float64(2.23606797749979), np.float64(1.5811388300841898)]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q14**: Delete the second column from an array and insert a new column at the same position where each value is the sum of its corresponding row.

In [113]:
input = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


def question_14(input):
    new_col = np.array([ np.sum(input[i]) for i in range(input.shape[0])])
    input = np.delete(input, 1, axis = 1)
    print(new_col)
    input = np.insert(input, 1, new_col, axis=1)
    return input


q14_sol = question_14(input)
q14.check()

[ 6 15 24]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q15**: Extract Unique Characters from a NumPy Array of Strings
Given a 1D NumPy array of strings, extract all unique characters present in the array and sort by their ASCII values.

In [2]:
input = np.array(["hello", "world", "numpy", "rocks"])


def question_15(input):
    chars = ''
    for i in input:
        chars += i
    chars_array = np.unique(list(chars))
    print(chars_array)
    return set(chars_array) # np.unique already sort the array


q15_sol = question_15(input)
q15.check()

['c' 'd' 'e' 'h' 'k' 'l' 'm' 'n' 'o' 'p' 'r' 's' 'u' 'w' 'y']


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q16**: Generate a dictionary that maps each unique character to a unique index starting with 0, sorted by ascending ASCII value.

In [ ]:
input = np.array(["a", "b", "c", "d", "a", "c", "e"])


def question_16(input):
    input = np.unique(input)
    dict = { input[i]: i for i in range(len(input)) }
    return dict


q16_sol = question_16(input)
q16.check()

{np.str_('a'): 0, np.str_('b'): 1, np.str_('c'): 2, np.str_('d'): 3, np.str_('e'): 4}


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q17**: Convert a List of 2D traces into a Single NumPy Array
Given a list of 2D traces (each being a NumPy array of shape `(N, 2)`), stack them into a single NumPy array.

In [ ]:
input = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8], [9, 10]])]


def question_17(input):
    arr = np.concatenate( (input[0], input[1]), axis = 0)
    return arr
    


q17_sol = question_17(input)
q17.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q18**: Convert a List of Text Labels into a NumPy Array of Integer Encodings
Given a vocabulary dictionary and a string of space-separated labels, convert the text into a NumPy array of indices.

In [27]:
input = {
    "hello": 0,
    "numpy": 1,
    "rocks": 2,
    "world": 3,
    "python": 4,
    "data": 5,
    "science": 6,
}

labels = "hello rocks"



def question_18(input, labels):
    return np.array( [input[key] for key in labels.split(" ")] )


q18_sol = question_18(input, labels)
q18.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q19**: Extract Non-Zero Differences from an Array
Given a NumPy array of first-order differences, extract only non-zero differences using masking.

In [17]:
input = np.array([[3, 4], [0, 0], [-2, 1]])


def question_19(input):

    # [[0,0]] not included = sure, but how about [[0,1]] ?
    return np.array([ arr for arr in input if np.sum(arr) != 0  ])


q19_sol = question_19(input)
q19.check()
q19.hint()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

<IPython.core.display.Javascript object>

<span style="color:#3366cc">Hint:</span> Create a mask to filter out rows that are all zeros and use it to index the array.

In [28]:
data = np.array(
    [
        [1.0, 10.0, 100.0],
        [2.0, 20.0, 200.0],
        [3.0, 30.0, 10000.0],  # Outlier in third column
        [4.0, 40.0, 400.0],
        [5.0, 50.0, 500.0],
    ]
)
# 1. Normalize the data.
mean_data = np.mean(data, axis=0)
std_data = np.std(data, axis=0)
std_data[std_data == 0] = 1
normalized_data = (data - mean_data) / std_data
# 2. Detect anomalies (>2.5 std) and mask them with NaN.
anomalies = np.abs(normalized_data) > 2.5
data_with_nan = data.copy()
data_with_nan[anomalies] = np.nan
print(data_with_nan)

# 3. Interpolate missing values (fill NaN with column mean).
interpolated_data = np.where(
    np.isnan(data_with_nan), np.nanmean(data_with_nan, axis=0), data_with_nan
)
print(interpolated_data)
# 4. Compute first-order differences.
first_order_diff = np.diff(interpolated_data, axis=0)
first_order_diff_padded = np.vstack(
    (first_order_diff, np.zeros((1, first_order_diff.shape[1])))
)
# 5. Create a missing flag.
missing_flag = np.isnan(data_with_nan).astype(int)

[[1.e+00 1.e+01 1.e+02]
 [2.e+00 2.e+01 2.e+02]
 [3.e+00 3.e+01 1.e+04]
 [4.e+00 4.e+01 4.e+02]
 [5.e+00 5.e+01 5.e+02]]
[[1.e+00 1.e+01 1.e+02]
 [2.e+00 2.e+01 2.e+02]
 [3.e+00 3.e+01 1.e+04]
 [4.e+00 4.e+01 4.e+02]
 [5.e+00 5.e+01 5.e+02]]


## **Q20**: Time Series Data Transformation and Feature Engineering

### *Problem Statement:*  
You are given a time series dataset representing sensor readings from multiple devices. Each row consists of sensor values at a specific timestamp. Your task is to preprocess and extract meaningful features from the dataset by performing the following transformations:

### *Steps to Follow:*
1. Normalize Each Sensor Reading  
- Subtract the mean and divide by the standard deviation for each column.  
- Avoid division by zero by replacing std=0 with 1.  
2. Detect and Mask Anomalous Values
- If a sensor reading is more than 2.5 standard deviations away from the mean, replace it with NaN.
3. Interpolate Missing Values (NaN Handling)
- Fill NaN values with the average of the nearest non-NaN neighbors.
4. Extract First-Order Differences
- Compute the difference between consecutive time steps for each sensor.
5. Add a Binary Column for Missing Data
- Stack All Features into a Final Matrix
Create a new column `missing_flag` that is `1` where original data was `NaN`, otherwise `0`.
6. Stack All Features into a Final Matrix
- The final dataset should have normalized values, moving averages, first-order differences, and the missing flag.

In [31]:
input = np.array(
    [
        [1.0, 10.0, 100.0],
        [2.0, 20.0, 200.0],
        [3.0, 30.0, 10000.0],  # Outlier in third column
        [4.0, 40.0, 400.0],
        [5.0, 50.0, 500.0],
    ]
)




def question_20(input):
    row = input.shape[0]
    col = input.shape[1]
    #1: Caluculate the mean and std_deviation
    mean = np.mean(input, axis = 0)
    std = np.std(input, axis = 0) 
    std = [value if value != 0 else 1 for value in std ]
    normalized_arr =  (input - mean)/std

    #2: Detect and mask anomoly
    data_with_nan = input.copy()
    for i in range(row):
        for u in range(col):
            if np.abs(normalized_arr[i][u]) > 2.5 :
                data_with_nan[i][u] = np.nan    

    #3 Replace with non NAN neighbor value
    col_means = np.nanmean(data_with_nan, axis=0) 
    col_means = np.where(np.isnan(col_means), 0, col_means) # In case all elements in collumn is nan, then mean is 0
    interpolated_data = np.where(np.isnan(data_with_nan), col_means, data_with_nan)
    #4: What collumn is time step ??
    first_order_diff = np.diff(interpolated_data, axis=0)

    first_order_diff_padded = np.vstack(
        (first_order_diff, np.zeros((1, first_order_diff.shape[1])))
    )

    #5: Binary column for missing data
    missing_flag = np.isnan(data_with_nan).astype(int)
    #print("Missing Flag: \n", missing_flag)
    
    #6
    final_arr = np.hstack((interpolated_data, first_order_diff_padded))
    final_arr = np.hstack((final_arr, missing_flag))
    return final_arr

        
q20_sol = question_20(input)
q20.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>